import localFont from "next/font/local";
import type { Metadata } from "next";
import RootProvider from "@/pr/providers/RootProvider";
import { ChildContainerProps } from "@/pr/types";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildContainerProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script id="primereact-tailwind" strategy="beforeInteractive">
          {`  const style = document.createElement('style')
              style.innerHTML = '@layer tailwind-base, primereact, tailwind-utilities;'
              style.setAttribute('type', 'text/css')
              document.querySelector('head').prepend(style)`}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-screen overflow-x-hidden`}
      >
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
